name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"  # 每 10 分钟触发一次

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Create timestamped .md file
        run: |
          timestamp=$(date "+%Y-%m-%d_%H-%M-%S")
          echo "hello world" > "$timestamp.md"

      - name: Commit and push .md file
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add *.md
          git commit -m "Add file $(date '+%Y-%m-%d_%H-%M-%S').md" || exit 0
          git push origin main
